version: 0.2

phases:
  install:
    commands:
      - make deps deps-test
  pre_build:
    commands:
      - chmod +x scripts/*.sh test/*/*.sh
  build:
    commands:
      - make test-integration-$AEM_VERSION-$OS_TYPE test_id=$BUILD_ID
