AWSTemplateFormatVersion: '2010-09-09'
Description: Create DNS Record Set in Route53 for AEM App Stacks
Parameters:
  AuthorDNSRecordSetNameParameter:
    Description: Author DNS Record Set Name
    Type: String
  AuthorDispatcherDNSRecordSetNameParameter:
    Description: AuthorDispatcher DNS Record Set Name
    Type: String
  MainStackPrefixParameter:
    Description: The AEM Stack Compute Resources Stack Prefix
    Type: String
  PublishDispatcherDNSRecordSetNameParameter:
    Description: PublishDispatcher DNS Record Set Name
    Type: String
  Route53HostedZoneNameParameter:
    Description: Route53 Hosted Zone Name the Record Set will be Created in
    Type: String
Resources:
  AuthorDispatcherRoute53RecordSet:
    Properties:
      HostedZoneName:
        Ref: Route53HostedZoneNameParameter
      Name:
        Fn::Sub: ${AuthorDispatcherDNSRecordSetNameParameter}.${Route53HostedZoneNameParameter}
      ResourceRecords:
      - Fn::ImportValue:
          Fn::Sub: ${MainStackPrefixParameter}-AuthorDispatcherLoadBalancerDNSName
      TTL: 300
      Type: CNAME
    Type: AWS::Route53::RecordSet
  AuthorRoute53RecordSet:
    Properties:
      HostedZoneName:
        Ref: Route53HostedZoneNameParameter
      Name:
        Fn::Sub: ${AuthorDNSRecordSetNameParameter}.${Route53HostedZoneNameParameter}
      ResourceRecords:
      - Fn::ImportValue:
          Fn::Sub: ${MainStackPrefixParameter}-AuthorLoadBalancerDNSName
      TTL: 300
      Type: CNAME
    Type: AWS::Route53::RecordSet
  PublishDispatcherRoute53RecordSet:
    Properties:
      HostedZoneName:
        Ref: Route53HostedZoneNameParameter
      Name:
        Fn::Sub: ${PublishDispatcherDNSRecordSetNameParameter}.${Route53HostedZoneNameParameter}
      ResourceRecords:
      - Fn::ImportValue:
          Fn::Sub: ${MainStackPrefixParameter}-PublishDispatcherLoadBalancerDNSName
      TTL: 300
      Type: CNAME
    Type: AWS::Route53::RecordSet
