AWSTemplateFormatVersion: '2010-09-09'
Description: Create Messaging resources for the AEM Stack Auto Scaling Group Events
Outputs:
  AEMASGEventQueueName:
    Description: The AEM ASG Event Queue Name
    Export:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-AEMASGEventQueueName
    Value:
      Fn::GetAtt: AEMAutoScalingGroupEventQueue.QueueName
  AEMASGEventTopic:
    Description: The AEM ASG Event Topic
    Export:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-AEMASGEventTopic
    Value:
      Ref: AEMASGEventTopic
  AEMAutoScalingGroupEventQueue:
    Description: The AEM ASG Event Queue
    Value:
      Ref: AEMAutoScalingGroupEventQueue
  AlarmNotificationTopic:
    Description: The AEM Alarm Notification Topic
    Export:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-AlarmNotificationTopic
    Value:
      Ref: AlarmNotificationTopic
Parameters:
  AEMASGEventQueueNameParameter:
    Description: The AEM Stack Auto Scaling Group Event Quene Name
    Type: String
  AEMASGEventTopicDisplayNameParameter:
    Description: The AEM Stack Auto Scaling Group Event Topic Display Name
    Type: String
  AEMASGEventTopicNameParameter:
    Description: The AEM Stack Auto Scaling Group Event Topic Name
    Type: String
  AEMCWEventNotificationEmail:
    Description: The EMail adress for sending CW Alarm messages
    Type: String
  PrerequisitesStackPrefixParameter:
    Description: The AEM Stack Prerequisite Resources Stack Prefix
    Type: String
Resources:
  AEMASGEventQueueLengthHighAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
      - Ref: AlarmNotificationTopic
      AlarmDescription: Alarm if queue length avg > 10 for 2 minutes
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: QueueName
        Value:
          Ref: AEMASGEventQueueNameParameter
      EvaluationPeriods: 2
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Period: 60
      Statistic: Average
      Threshold: 10
      TreatMissingData: ignore
    Type: AWS::CloudWatch::Alarm
  AEMASGEventQueuePolicy:
    Properties:
      PolicyDocument:
        Statement:
        - Action:
          - sqs:SendMessage
          Condition:
            ArnEquals:
              aws:SourceArn:
                Ref: AEMASGEventTopic
          Effect: Allow
          Principal:
            AWS: '*'
          Resource:
          - Fn::GetAtt:
            - AEMAutoScalingGroupEventQueue
            - Arn
        Version: '2012-10-17'
      Queues:
      - Ref: AEMAutoScalingGroupEventQueue
    Type: AWS::SQS::QueuePolicy
  AEMASGEventTopic:
    Properties:
      DisplayName:
        Ref: AEMASGEventTopicDisplayNameParameter
      Subscription:
      - Endpoint:
          Fn::GetAtt:
          - AEMAutoScalingGroupEventQueue
          - Arn
        Protocol: sqs
      TopicName:
        Ref: AEMASGEventTopicNameParameter
    Type: AWS::SNS::Topic
  AEMAutoScalingGroupEventQueue:
    Properties:
      QueueName:
        Ref: AEMASGEventQueueNameParameter
      VisibilityTimeout: 60
    Type: AWS::SQS::Queue
  AlarmNotificationTopic:
    Properties:
      DisplayName:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-alarm-notification-topic
      Subscription:
      - Endpoint:
          Ref: AEMCWEventNotificationEmail
        Protocol: email
    Type: AWS::SNS::Topic
